package com.jsict.biz.dao.impl;

import com.jsict.biz.dao.ConfigDao;
import com.jsict.biz.model.Config;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import org.springframework.stereotype.Repository;


/**
* Auto-Generated by UDP Generator
*/
@Repository
public class ConfigDaoImpl extends GenericHibernateDaoImpl<Config, String> implements ConfigDao {

/**
 * 示例代码
 * @Override
 * public Config save(Config entity){
 * return super.save(entity);
 * }
 */
}
