package com.jsict.biz.service;

import com.jsict.biz.model.Config;
import com.jsict.framework.core.service.GeneriService;


/**
 * Auto-Generated by UDP Generator
 */
public interface ConfigService extends GeneriService<Config, String> {
}
