package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.Department;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface DepartmentService extends GeneriService<Department, String> {


}
