package com.jsict.biz.service.impl;

import com.jsict.biz.model.Config;
import com.jsict.biz.service.ConfigService;
import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import org.springframework.stereotype.Service;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class ConfigServiceImpl extends GeneriServiceImpl<Config, String> implements ConfigService {
/**
 * 示例代码
 * @Override
 * @Transactional
 * public Config save(Config entity) {
 * return super.save(entity);
 * }
 */
}
