package com.jsict.biz.service.impl;

import com.jsict.biz.service.CodeService;
import com.jsict.framework.core.security.UdpShiroFilterFactoryBean;
import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import com.jsict.biz.model.Department;
import com.jsict.biz.service.DepartmentService;

import com.jsict.framework.utils.SpringContextUtil;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class DepartmentServiceImpl extends GeneriServiceImpl<Department, String> implements DepartmentService {


}