package com.jsict.biz.model;

import com.jsict.framework.core.dao.annotation.LogicDel;
import com.jsict.framework.core.model.BaseEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * Auto-Generated by UDP Generator
 */
@LogicDel
@Entity
@Table(name = "config")
public class Config extends BaseEntity<String> {

    /** key */
    @Column(name = "keyy", length = 255)
    private String keyy;
    /** value */
    @Column(name = "valuee", length = 255)
    private String valuee;
    /** level
     * 2 为用户可修改的配置  空为管理员才能修改的配置
     * */
    @Column(name = "levell", length = 255)
    private String levell ;
    /** name */
    @Column(name = "name", length = 255)
    private String name ;

    /** canbedelete */
    @Column(name = "canbedelete", length = 255)
    private String canbedelete ;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCanbedelete() {
        return canbedelete;
    }

    public void setCanbedelete(String canbedelete) {
        this.canbedelete = canbedelete;
    }

    public void setKeyy(String key){
        this.keyy = key;
    }

    public String getKeyy(){
        return this.keyy;
    }
    public void setValuee(String value){
        this.valuee = value;
    }

    public String getValuee(){
        return this.valuee;
    }

    public String getLevell() {
        return levell;
    }

    public void setLevell(String levell) {
        this.levell = levell;
    }
}