package com.jsict.biz.controller;

import com.jsict.biz.dao.DepartmentDao;
import com.jsict.biz.dao.UserDao;
import com.jsict.biz.model.Department;
import com.jsict.biz.model.Role;
import com.jsict.biz.service.UserService;
import com.jsict.framework.core.controller.AbstractGenericController;
import com.jsict.biz.model.User;

import com.jsict.framework.core.controller.CSRFTokenManager;
import com.jsict.framework.core.controller.Response;
import com.jsict.framework.core.controller.RestControllerException;
import com.jsict.framework.core.security.model.IUser;
import com.jsict.framework.filter.EscapeScriptwrapper;
import com.jsict.framework.utils.Identities;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.web.servlet.ShiroHttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.web.bind.annotation.*;
import org.springframework.stereotype.Controller;

import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;


/**
 * Auto-Generated by UDP Generator
 */
@Controller
@RequestMapping("/user")
public class UserController extends
    AbstractGenericController<User, String,
            User> {

    private static final Logger logger = LoggerFactory.getLogger(UserController.class);

    @Autowired
    private UserDao userDao;

    @Autowired
    private DepartmentDao departmentDao;

   /**
    *
    * 功能描述: 保存用户
    *
    * @param:
    * @return: 
    * @auther: Lv
    * @date: 2019/2/25 15:39
    */
    @Override
    @RequestMapping(value = "/save", method = RequestMethod.POST, produces = "application/json")
    @ResponseBody
    public Response save(@ModelAttribute User entity, @RequestParam(value = CSRFTokenManager.CSRF_PARAM_NAME) String paramToken, HttpServletRequest request){
        Map<String,Object> params = new HashMap<>();
        params.put("delFlag",0);
        params.put("userId",entity.getUserId());
        List<User> list = userDao.getObjectListBySqlKey("getListByUserId",params,User.class);
        if(list != null && list.size() > 0){
            return new Response(ERROR,"用户名已经存在");
        }
        //保存用户照片方法在super.save里面调用
        return super.save(entity, paramToken, request);
    }

    /**
     *
     * 功能描述: 编辑用户
     *
     * @param:
     * @return:
     * @auther: Lv
     * @date: 2019/2/25 16:56
     */
    @Override
    @RequestMapping(value = "/update", method = RequestMethod.POST, produces = "application/json")
    @ResponseBody
    public Response update(@ModelAttribute User entity, @RequestParam(value = CSRFTokenManager.CSRF_PARAM_NAME) String paramToken, HttpServletRequest request){
        User db = this.generiService.getWithoutDic(entity.getId());
        if(!entity.getUserId().equals(db.getUserId())){
            Map<String,Object> params = new HashMap<>();
            params.put("delFlag",0);
            params.put("userId",entity.getUserId());
            List<User> list = userDao.getObjectListBySqlKey("getListByUserId",params,User.class);
            if(list != null && list.size() > 0){
                return new Response(ERROR,"用户名已经存在");
            }
        }
        return super.update(entity, paramToken, request);
    }

    @RequestMapping(value = {"/getUserForUpdate/{id}"}, method = {RequestMethod.GET}, produces = {"application/json"})
    @ResponseBody
    public User get(@PathVariable String id) {
        try {
            User user = this.generiService.getWithoutDic(id);
            Map<String,Object> params = new HashMap<>();
            params.put("delFlag",0);
            params.put("type",user.getType());
            List<Department> list = departmentDao.getObjectListBySqlKey("getListByNameCode",params,Department.class);
            user.setSelectDeptList(list);
            return user;
        } catch (Exception var3) {
            logger.error("主键查询出错", var3);
            throw new RestControllerException("主键查询出错", var3);
        }
    }

    @ResponseBody
    @RequestMapping(value = "/clearUserLock", method = RequestMethod.POST)
    public Response clearUserLock(@RequestParam String id){
        try{
            ((UserService)generiService).clearUserLock(id);
            return new Response(0);
        }catch(Exception e){
            logger.debug("解除用户锁定出错", e);
            return new Response(-1, e.getMessage());
        }
    }

    @ResponseBody
    @RequestMapping(value = "/initPassword", method = RequestMethod.POST)
    public Response initPassword(@RequestParam String id){
        try{
            ((UserService)generiService).initPassword(id);
            return new Response(0);
        }catch(Exception e){
            logger.debug("初始化密码出错", e);
            return new Response(-1, e.getMessage());
        }
    }

    @Override
    @RequestMapping(value = "/page", method = RequestMethod.POST, produces = "application/json")
    @ResponseBody
    public Page<User> page(@ModelAttribute User query, @PageableDefault Pageable pageable){
        try{
            return generiService.findByPage(query, pageable);
        }catch(Exception e){
            logger.error("翻页查询出错", e);
            throw new RestControllerException("翻页查询出错", e);
        }
    }

    /**
     *
     * 功能描述: 获取所有科室部门
     *
     * @param:
     * @return:
     * @auther: Lv
     * @date: 2019/2/23 17:41
     */
    @RequestMapping(value = "/getDept", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    public List<Department> getDept(){
        Map<String,Object> params = new HashMap<>();
        params.put("delFlag",0);
        List<Department> list = departmentDao.getObjectListBySqlKey("getListByNameCode",params,Department.class);
        return list;
    }

    /**
     *
     * 功能描述: 获取科室或者患者部门
     *
     * @param:
     * @return:
     * @auther: Lv
     * @date: 2019/2/25 10:27
     */
    @RequestMapping(value = "/getDeptList", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    public List<Department> getDeptList(String type){
        Map<String,Object> params = new HashMap<>();
        params.put("delFlag",0);
        params.put("type",type);
        List<Department> list = departmentDao.getObjectListBySqlKey("getListByNameCode",params,Department.class);
        return list;
    }

    @ResponseBody
    @RequestMapping(value = "/enable", method = RequestMethod.POST)
    public Response enable(@RequestParam String id){
        try{
            ((UserService)generiService).enable(id);
            return new Response(0);
        }catch(Exception e){
            logger.debug("激活用户出错", e);
            return new Response(-1, e.getMessage());
        }
    }

    @ResponseBody
    @RequestMapping(value = "/disable", method = RequestMethod.POST)
    public Response disable(@RequestParam String id){
        try{
            ((UserService)generiService).disable(id);
            return new Response(0);
        }catch(Exception e){
            logger.debug("禁用用户出错", e);
            return new Response(-1, e.getMessage());
        }
    }

    @RequestMapping(value = "/queryUsers", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    public List<Role> queryUsers(@RequestParam String userQuery){
        Map<String, Object> params = new HashMap<>();
        params.put("name", userQuery);
        params.put("userId",userQuery);
        return userDao.find("selectByPage", params);
    }

    @Override
    protected void uploadFile(User user, HttpServletRequest request) throws IOException {
      String allowedFiles = this.sysConfig.getConfig().getString("allowedFiles");
      List<String> allowedFileList = new ArrayList();
      if (StringUtils.isNotBlank(allowedFiles)) {
        allowedFileList.addAll(Arrays.asList(allowedFiles.split("\\|")));
      }
      List<String> paths = new ArrayList<>();
      String uploadPath = "/userImg";
      MultipartHttpServletRequest multipartReq = (MultipartHttpServletRequest)request;
      List<MultipartFile> multipartFileList = multipartReq.getFiles("file");
      //此处只有一个文件，多文件需要遍历
      for (MultipartFile f : multipartFileList) {
        File fileDir = new File(uploadPath);
        if(!fileDir.exists())
          fileDir.mkdirs();
        //文件原始名
        String originalFilename = f.getOriginalFilename();
        //新文件名
        int pos = originalFilename.lastIndexOf('.');
        String suffix = originalFilename.substring(pos+1);
        String fileName = Identities.uuid2() + "." + suffix;

        if(!allowedFileList.contains(suffix))
          throw new RestControllerException("上传文件文件格式不合法，支持的文件格式为：" + allowedFiles.replace("|", "、"));

        File targetFile = new File(fileDir, fileName);
        FileUtils.copyInputStreamToFile(f.getInputStream(), targetFile);
        paths.add(uploadPath+"/"+fileName);
      }
      if (paths != null && paths.size()>0){
        String s = "";
        for (int i = 0;i<paths.size();i++){
          if (i<paths.size()-1){
            s += paths.get(i) + ",";
          }else {
            s += paths.get(i);
          }
        }
        user.setPhoto(s);
      }

    }

}