package com.jsict.biz.dao;

import com.jsict.biz.model.Config;
import com.jsict.framework.core.dao.GenericDao;


/**
* Auto-Generated by UDP Generator
*/
public interface ConfigDao extends GenericDao<Config, String> {
}